// =====================================================================
//  GENERATED by sync-components.mjs from components/*.part.tsx.
//  Do not edit here: edit the parts and re-run `node sync-components.mjs`.
// =====================================================================

import React, { useEffect, useMemo, useRef, useState } from "react";
import { Controls, Given, runData, useGiven, useQuery, useUrlState, filters } from "@malloyyo/dashboard";

// =====================================================================
//  Drive chart — the React/SVG chart from ../dashboards/team-drive-charts.tsx,
//  vendored here so this project stands on its own. sync-components.mjs
//  splices it into every games report component (a malloyyo component
//  may import only React and @malloyyo/dashboard, never a local module).
// =====================================================================

// ---- palette -------------------------------------------------------
// Read off the reference chart: scoring drives carry the saturated
// hues, a drive that LOST ground goes orange, everything else recedes
// to grey. Identity never rests on color — every drive is labelled.
const NAVY = "#1c3557";     // touchdown
const BLUE = "#5b8fd6";     // field goal
const ORANGE = "#e2703a";   // the drive lost yardage
const GREY = "#b3b3b3";     // punt, turnover, clock
const KO_GREY = "#c9ccd0";  // kickoff markers and the dashed routing
const INK = "#1a1c1f";
const MUTED = "#9aa0a6";
const RULE = "#d7dade";

// ---- layout --------------------------------------------------------
const COL = 30;          // per possession — tight, so a whole game fits
const HALF_GAP = 34;     // the break between halves
const REG_GAP = 40;      // the break before overtime; its label stacks to fit
const LABEL_W = 96;      // ledger row labels down the left
const AXIS_W = 24;       // yard numbers, repeated on both sides
const PLOT_PAD = 26;     // room for the opening kickoff, which is routed
                         // in from the LEFT of the first possession
const FINAL_W = 46;      // the "Final" column
const FIELD_H = 300;
const FIELD_TOP = 26;
const LEDGER_TOP_PAD = 16;
const ROW_H = 21;
const RETURN_DX = 10;    // a return touchdown sits this far right of the possession

/** Team names as they arrive from two different givens — compare loosely. */
const sameTeam = (a: string, b: string) =>
  String(a || "").trim().toLowerCase() === String(b || "").trim().toLowerCase();

const teamWords = (t: string) =>
  String(t || "").replace(/[^A-Za-z0-9 ]/g, " ").trim().split(/\s+/).filter(Boolean);

/**
 * Three-character tags for a team, in the order we would rather use them.
 * The first is the plain one — Alabama becomes Ala — and the rest are
 * fallbacks that reach into the second and third words for teams whose
 * first word is not enough on its own.
 */
const tagCandidates = (t: string): string[] => {
  const w = teamWords(t);
  if (!w.length) return [""];
  const squashed = w.join("");
  const raw = [w[0].slice(0, 3)];
  if (w[1]) raw.push(w[0][0] + w[1].slice(0, 2));
  if (w[1]) raw.push(w[0].slice(0, 2) + w[1][0]);
  if (w[2]) raw.push(w[0][0] + w[1][0] + w[2][0]);
  // For one-word names the fallbacks above have nothing to reach for, so
  // reach further into the word itself — Tulane and Tulsa are both "Tul".
  raw.push(w[0][0] + w[0].slice(3, 5));
  raw.push(w[0].slice(0, 2) + w[0].slice(-1));
  raw.push(squashed.slice(0, 3));
  // The plain tag stands as it is — UC Davis has always read "UC" and
  // there is nothing wrong with it. Only the FALLBACKS, which exist to
  // break a tie, are held to three characters: a one-letter second word
  // would otherwise offer "TA" for Texas A&M, no clearer than what it
  // was replacing.
  const out = [raw[0], ...raw.slice(1).filter((c) => c.length === 3)];
  return out.filter((c, i) => c && out.indexOf(c) === i);
};

/**
 * Tags for the two teams of one game, guaranteed to differ from each other
 * wherever the names allow it. South Dakota and Southern Illinois both come
 * out "Sou" under the plain rule, which left every column of the possession
 * row in that game reading the same three letters — so the pair steps down
 * its fallbacks together until they part: SDa and SIl.
 */
const gameTags = (awayTeam: string, homeTeam: string): [string, string] => {
  const a = tagCandidates(awayTeam);
  const h = tagCandidates(homeTeam);
  if (a[0] !== h[0]) return [a[0], h[0]];

  // A one-word name against a longer one that starts the same way —
  // Michigan and Michigan State — has an obvious reading: the short name
  // keeps the plain tag and only the longer one steps aside, giving
  // Mic and MSt rather than two equally strange halves.
  const aWords = teamWords(awayTeam).length;
  const hWords = teamWords(homeTeam).length;
  if (aWords === 1 && hWords > 1) {
    const ht = h.find((c) => c !== a[0]);
    if (ht) return [a[0], ht];
  }
  if (hWords === 1 && aWords > 1) {
    const at = a.find((c) => c !== h[0]);
    if (at) return [at, h[0]];
  }

  // Otherwise both step down together, so the pair reads as a pair:
  // South Dakota and Southern Illinois become SDa and SIl.
  const depth = Math.max(a.length, h.length);
  for (let i = 1; i < depth; i++) {
    const at = a[Math.min(i, a.length - 1)];
    const ht = h[Math.min(i, h.length - 1)];
    if (at !== ht) return [at, ht];
  }
  // two teams the name itself cannot separate; the plain tag is as good as any
  return [a[0], h[0]];
};

const driveColor = (d: any) => {
  if (d.result_category === "Touchdown") return NAVY;
  if (d.result_category === "Field goal") return BLUE;
  // a possession that ended behind where it started
  if (Number(d.yards) < 0) return ORANGE;
  return GREY;
};

/** Rounded orthogonal path through a list of points. */
function routePath(pts: [number, number][], r = 7) {
  if (pts.length < 2) return "";
  let d = `M ${pts[0][0]} ${pts[0][1]}`;
  for (let i = 1; i < pts.length - 1; i++) {
    const [px, py] = pts[i - 1];
    const [cx, cy] = pts[i];
    const [nx, ny] = pts[i + 1];
    const inLen = Math.hypot(cx - px, cy - py);
    const outLen = Math.hypot(nx - cx, ny - cy);
    const ri = Math.min(r, inLen / 2, outLen / 2);
    const ix = cx - ((cx - px) / (inLen || 1)) * ri;
    const iy = cy - ((cy - py) / (inLen || 1)) * ri;
    const ox = cx + ((nx - cx) / (outLen || 1)) * ri;
    const oy = cy + ((ny - cy) / (outLen || 1)) * ri;
    d += ` L ${ix} ${iy} Q ${cx} ${cy} ${ox} ${oy}`;
  }
  const last = pts[pts.length - 1];
  d += ` L ${last[0]} ${last[1]}`;
  return d;
}

// =====================================================================
//  The chart
// =====================================================================
export type DriveOrient = "up" | "down" | "default";

export function DriveChart({
  game,
  focusTeam,
  orient = "up",
}: {
  game: any;
  /** The team the reader picked, whose possessions get pointed a chosen way. */
  focusTeam?: string;
  /** Which way the picked team drives: up, down, or "default" for the
      fixed convention — home attacks down in every game. */
  orient?: DriveOrient;
}) {
  const [hover, setHover] = useState<{ d: any; x: number; y: number } | null>(null);

  const drives = game.rows;
  const home = game.home_team;
  const away = game.away_team;

  // WHICH WAY IS UP.
  //
  // In field coordinates the home team always attacks 100 and the away team
  // 0, so on an unflipped field the home team drives DOWN the page and the
  // away team up. Read a season one team at a time and that convention
  // fights you: the same offense climbs in one game and falls in the next,
  // for no reason the reader cares about.
  //
  // So the reader points the picked team a fixed way and the chart turns
  // itself over in whichever games it needs to — its home games to send it
  // up, its away games to send it down. "default" opts out and restores the
  // fixed convention, which is what you want when reading the GAME rather
  // than following one team.
  //
  // Every piece of geometry below reads the field through yFor — drives,
  // kickoff markers, the dashed routing, the yard numbers — so this one
  // line flips the entire chart and nothing else has to know.
  const flip =
    !focusTeam || orient === "default"
      ? false
      : orient === "up"
        ? sameTeam(focusTeam, home)
        : sameTeam(focusTeam, away);
  const yFor = (yardline: number) =>
    FIELD_TOP + ((flip ? 100 - yardline : yardline) / 100) * FIELD_H;

  // Two structural breaks split the x spacing: halftime, and — when the
  // game went past the fourth quarter — the end of regulation. Overtime is
  // a different game with different rules, so it reads as its own block.
  const firstSecondHalf = drives.findIndex((d: any) => Number(d.start_period) >= 3);
  const firstOvertime = drives.findIndex((d: any) => Number(d.start_period) >= 5);
  /** Total break width sitting to the LEFT of possession i. */
  const gapBefore = (i: number) =>
    (firstSecondHalf > 0 && i >= firstSecondHalf ? HALF_GAP : 0) +
    (firstOvertime > 0 && i >= firstOvertime ? REG_GAP : 0);
  const xFor = (i: number) =>
    LABEL_W + AXIS_W + PLOT_PAD + i * COL + COL / 2 + gapBefore(i);

  const width =
    LABEL_W + AXIS_W + PLOT_PAD + drives.length * COL +
    gapBefore(drives.length) + FINAL_W + AXIS_W;
  const fieldBottom = FIELD_TOP + FIELD_H;
  const ledgerTop = fieldBottom + LEDGER_TOP_PAD;
  const height = ledgerTop + ROW_H * 4 + 14;

  // ---- kickoffs and the dashed routing between possessions ----------
  const links = useMemo(() => {
    const out: { path: string; ko: { x: number; y: number } | null }[] = [];
    for (let i = 0; i < drives.length; i++) {
      const cur = drives[i];
      const prev = i > 0 ? drives[i - 1] : null;

      // OVERTIME HAS NO KICKOFFS. Each possession is spotted on the
      // opponent's 25 and the ball never leaves the offense's hands to a
      // kicking team, so there is no kickoff to mark and nothing for a
      // dashed line to trace — neither between overtime possessions nor
      // from the last play of regulation into the first of overtime, which
      // is a break like halftime. Drawing them there invented a play that
      // was never run.
      if (Number(cur.start_period) >= 5) continue;
      const startsSecondHalf = !!prev && Number(prev.start_period) <= 2 && Number(cur.start_period) >= 3;
      const startsHalf = i === 0 || startsSecondHalf;
      const prevOffScored = prev ? Number(prev.drive_points) > 0 : false;
      const prevDefTd = prev ? Number(prev.defensive_points_scored) >= 6 : false;
      const prevSafety = prev ? Number(prev.defensive_points_scored) === 2 : false;
      const prevSpecialTeams = !!prev && !!prev.is_special_teams_touchdown;
      const prevPutPointsUp = prevOffScored || prevDefTd || prevSafety || prevSpecialTeams;

      // Who kicks: whoever just scored. On a defensive or special-teams
      // touchdown that is the team that was DEFENDING; after a safety it is
      // the team that was scored upon, which free-kicks. To open a half it
      // is whoever is about to defend.
      //
      // A KICKOFF RETURN row is the exception, because the feed files it
      // under the KICKING team: its "offense" is the team that kicked and
      // its "defense" is the team that ran it back.
      let kicker: string | null = null;
      if (cur.is_kickoff_return_touchdown) kicker = cur.offense;
      else if (prevOffScored) kicker = prev.offense;
      else if (prevDefTd || prevSpecialTeams) kicker = prev.defense;
      else if (prevSafety) kicker = prev.offense;
      else if (startsHalf) kicker = cur.defense;

      const x = xFor(i);
      const startY = yFor(Number(cur.start_yardline));

      if (!prev) {
        if (!kicker) continue;
        // opening kickoff: a short hook into the first possession
        const koY = yFor(kicker === home ? 35 : 65);
        const koX = x - COL * 0.62;
        out.push({
          path: routePath([[koX, koY], [koX - 1, koY], [x - COL * 0.3, koY], [x - COL * 0.3, startY], [x, startY]]),
          ko: { x: koX, y: koY },
        });
        continue;
      }

      const px = xFor(i - 1);
      const endY = yFor(Number(prev.end_yardline));
      const xa = px + COL * 0.36;
      const xb = x - COL * 0.36;

      if (kicker) {
        // The dotted line does NOT run out of a possession that scored,
        // nor across halftime: in both cases the ball is dead and goes
        // back to a kicking tee, so the route STARTS at the kickoff
        // marker. Nothing traces from the last play of the half to the
        // second-half kickoff.
        const koY = yFor(kicker === home ? 35 : 65);
        const koX = (xa + xb) / 2;
        const inbound =
          prevPutPointsUp || startsSecondHalf
            ? ""
            : routePath([[px, endY], [xa, endY], [xa, koY], [koX, koY]]) + " ";
        out.push({
          path: inbound + routePath([[koX, koY], [xb, koY], [xb, startY], [x, startY]]),
          ko: { x: koX, y: koY },
        });
      } else {
        // straight change of possession: the ball is where it is
        const mid = (px + x) / 2;
        out.push({ path: routePath([[px, endY], [mid, endY], [mid, startY], [x, startY]]), ko: null });
      }
    }
    return out;
  }, [drives, flip]);

  const yardLabels = [10, 20, 30, 40, 50, 60, 70, 80, 90];
  const fmtYard = (v: number) => (v > 50 ? 100 - v : v);

  // ---- ledger -------------------------------------------------------
  const rows = [
    { key: "poss", label: "Game Poss #" },
    { key: "team", label: "Possession" },
    { key: "away", label: away },
    { key: "home", label: home },
  ];
  const rowY = (n: number) => ledgerTop + n * ROW_H + ROW_H * 0.7;
  const halfX = firstSecondHalf > 0 ? xFor(firstSecondHalf) - COL / 2 - HALF_GAP / 2 : null;
  const regX = firstOvertime > 0 ? xFor(firstOvertime) - COL / 2 - REG_GAP / 2 : null;
  const finalX = xFor(drives.length - 1) + COL / 2 + FINAL_W / 2;
  const [awayTag, homeTag] = gameTags(away, home);
  const abbr = (t: string) => (sameTeam(t, home) ? homeTag : awayTag);

  return (
    <div style={{ position: "relative", overflowX: "auto" }}>
      <svg width={width} height={height} style={{ display: "block", fontFamily: "inherit" }}>
        {/* field boundaries and yard lines */}
        <line x1={LABEL_W + AXIS_W - 8} y1={FIELD_TOP} x2={width - AXIS_W} y2={FIELD_TOP} stroke={RULE} strokeWidth={1} />
        <line x1={LABEL_W + AXIS_W - 8} y1={fieldBottom} x2={width - AXIS_W} y2={fieldBottom} stroke={RULE} strokeWidth={1} />
        {yardLabels.map((v) => (
          <g key={v}>
            <line
              x1={LABEL_W + AXIS_W - 8}
              y1={yFor(v)}
              x2={width - AXIS_W}
              y2={yFor(v)}
              stroke="#f0f1f3"
              strokeWidth={1}
            />
            <text x={LABEL_W + AXIS_W - 12} y={yFor(v) + 3.5} textAnchor="end" fontSize={10} fill={MUTED}>
              {fmtYard(v)}
            </text>
            <text x={width - AXIS_W + 6} y={yFor(v) + 3.5} fontSize={10} fill={MUTED}>
              {fmtYard(v)}
            </text>
          </g>
        ))}

        {/* which way each team is driving, at its own end of the field */}
        <text x={LABEL_W + AXIS_W - 2} y={yFor(12)} fontSize={10.5} fill={MUTED}
          stroke="#fff" strokeWidth={3} paintOrder="stroke">{home} {flip ? "↑" : "↓"}</text>
        <text x={LABEL_W + AXIS_W - 2} y={yFor(90)} fontSize={10.5} fill={MUTED}
          stroke="#fff" strokeWidth={3} paintOrder="stroke">{away} {flip ? "↓" : "↑"}</text>

        {/* dashed routing and kickoff markers, behind the possessions */}
        {links.map((l, i) => (
          <g key={`k${i}`}>
            <path d={l.path} fill="none" stroke={KO_GREY} strokeWidth={1} strokeDasharray="3 3" />
            {l.ko && (
              <>
                <circle cx={l.ko.x} cy={l.ko.y} r={4} fill="#fff" stroke={KO_GREY} strokeWidth={1.4} />
                  <text
                  x={l.ko.x}
                  y={l.ko.y + 15}
                  textAnchor="middle"
                  fontSize={9}
                  fill={MUTED}
                  stroke="#fff"
                  strokeWidth={2.5}
                  paintOrder="stroke"
                >
                  KO
                </text>
              </>
            )}
          </g>
        ))}

        {/* the possessions */}
        {drives.map((d: any, i: number) => {
          const x = xFor(i);
          const y1 = yFor(Number(d.start_yardline));
          const y2 = yFor(Number(d.end_yardline));
          const color = driveColor(d);
          const scored = Number(d.drive_points) > 0;
          // A return touchdown belongs to the OTHER team, so it is drawn as
          // its own line to the goal line that team was attacking, a step to
          // the right of the possession rather than on top of it: dotted for
          // special teams (kickoff, punt, blocked kick), dashed for a defense
          // that took the ball away. A kickoff return has no possession to
          // draw at all — the feed's "drive" IS the return.
          const specialTeams = !!d.is_special_teams_touchdown;
          const kickoffReturn = !!d.is_kickoff_return_touchdown;
          const defensiveTd = !specialTeams && Number(d.defensive_points_scored) >= 6;
          const returnTd = specialTeams || defensiveTd;
          const returnY = yFor(d.is_home_offense ? 0 : 100);
          // a kickoff return starts where the ball was kicked from
          const returnFromY = kickoffReturn ? y1 : y2;
          // The possession keeps ITS own result. On a punt return the drive
          // still ended in a punt, so labelling it "ST TD" — the category the
          // return earned it — put the same words on both lines.
          const possessionLabel = !specialTeams
            ? d.result_abbreviation
            : d.special_teams_score_type === "Punt return"
              ? "P"
              : d.special_teams_score_type === "Blocked kick return"
                ? "FGA"
                : d.result_abbreviation;
          return (
            // NOT keyed on drive_number: the feed repeats it across overtime
            // possessions in a handful of games, and duplicate keys make React
            // reuse the wrong node. Position in this already-sorted list is
            // stable for as long as the list is.
            <g key={i}>
              {/* A kickoff return has no possession to draw: the feed's row
                  IS the return, filed under the kicking team. */}
              {!kickoffReturn && (
                <>
                  <line x1={x} y1={y1} x2={x} y2={y2} stroke={color} strokeWidth={2.5} strokeLinecap="round" />
                  <circle cx={x} cy={y1} r={3.2} fill={color} />
                  <circle cx={x} cy={y2} r={4.2} fill={color} />
                </>
              )}
              {/* The other team's touchdown, carried to the goal line THAT
                  team was attacking. Drawn a step to the right of the
                  possession rather than over it, and never solid: dotted for
                  special teams, dashed for a defense that took the ball away. */}
              {returnTd && (
                <g>
                  <line
                    x1={x + RETURN_DX}
                    y1={returnFromY}
                    x2={x + RETURN_DX}
                    y2={returnY}
                    stroke={NAVY}
                    strokeWidth={2}
                    strokeDasharray={specialTeams ? "1 3.5" : "4 3"}
                    strokeLinecap={specialTeams ? "round" : "butt"}
                  />
                  <circle cx={x + RETURN_DX} cy={returnFromY} r={3} fill="#fff" stroke={NAVY} strokeWidth={1.4} />
                  <circle cx={x + RETURN_DX} cy={returnY} r={4.2} fill={NAVY} />
                  <text
                    x={x + RETURN_DX + 6}
                    y={returnY + 3.5}
                    fontSize={9}
                    fontWeight={700}
                    fill={NAVY}
                    stroke="#fff"
                    strokeWidth={2.5}
                    paintOrder="stroke"
                  >
                    {specialTeams ? "ST TD" : "TD"}
                  </text>
                </g>
              )}
              {!kickoffReturn && (
                <text
                  x={x + 7}
                  y={y2 + 3.5}
                  fontSize={9}
                  fontWeight={scored ? 700 : 500}
                  fill={color === GREY ? MUTED : color}
                  stroke="#fff"
                  strokeWidth={2.5}
                  paintOrder="stroke"
                >
                  {possessionLabel}
                </text>
              )}
              {/* a wide invisible target so the tooltip is easy to hit */}
              <rect
                x={x - COL / 2}
                y={FIELD_TOP}
                width={COL}
                height={FIELD_H}
                fill="transparent"
                onMouseEnter={() => setHover({ d, x, y: Math.min(y1, y2) })}
                onMouseLeave={() => setHover(null)}
              />
            </g>
          );
        })}

        {/* ledger */}
        {rows.map((r, n) => (
          <text key={r.key} x={8} y={rowY(n)} fontSize={n >= 2 ? 12 : 10} fill={n >= 2 ? INK : MUTED}
            fontWeight={n >= 2 ? 700 : 400}>
            {r.label}
          </text>
        ))}
        {drives.map((d: any, i: number) => {
          const x = xFor(i);
          const prev = i > 0 ? drives[i - 1] : null;
          const awayScored = !prev || Number(d.away_score_after) !== Number(prev.away_score_after);
          const homeScored = !prev || Number(d.home_score_after) !== Number(prev.home_score_after);
          const teamScored = Number(d.drive_points) > 0;
          return (
            <g key={`l${i}`}>
              <text x={x} y={rowY(0)} textAnchor="middle" fontSize={10} fill={MUTED}>{d.drive_number}</text>
              <text x={x} y={rowY(1)} textAnchor="middle" fontSize={10}
                fill={teamScored ? INK : MUTED} fontWeight={teamScored ? 700 : 400}>
                {abbr(d.offense)}
              </text>
              <text x={x} y={rowY(2)} textAnchor="middle" fontSize={12}
                fill={awayScored && i > 0 ? INK : MUTED} fontWeight={awayScored && i > 0 ? 700 : 400}>
                {d.away_score_after}
              </text>
              <text x={x} y={rowY(3)} textAnchor="middle" fontSize={12}
                fill={homeScored && i > 0 ? INK : MUTED} fontWeight={homeScored && i > 0 ? 700 : 400}>
                {d.home_score_after}
              </text>
            </g>
          );
        })}
        {halfX !== null && (
          <text x={halfX} y={(rowY(2) + rowY(3)) / 2 + 2} textAnchor="middle" fontSize={12} fill={INK} fontWeight={600}>
            Half
          </text>
        )}
        {/* Only on games that went past the fourth quarter. The score
            standing here is the one that sent the game to overtime; the
            "Final" column at the far right is the one that ended it.
            Stacked over three lines so the break stays as narrow as
            halftime's — set on one line it pushed the overtime a third of
            the chart to the right. */}
        {regX !== null &&
          ["End", "of", "Reg."].map((line, n) => (
            <text
              key={line}
              x={regX}
              y={(rowY(2) + rowY(3)) / 2 + 2 + (n - 1) * 12}
              textAnchor="middle"
              fontSize={12}
              fill={INK}
              fontWeight={600}
            >
              {line}
            </text>
          ))}
        <text x={finalX} y={(rowY(2) + rowY(3)) / 2 + 2} textAnchor="middle" fontSize={12} fill={INK} fontWeight={600}>
          Final
        </text>
      </svg>

      {hover && (
        <div
          style={{
            position: "absolute",
            left: Math.min(hover.x + 12, width - 190),
            top: hover.y,
            pointerEvents: "none",
            background: "#ffffff",
            border: "1px solid #e5e7eb",
            boxShadow: "0 6px 20px rgba(15,20,30,0.14)",
            borderRadius: 7,
            padding: "8px 10px",
            fontSize: 11.5,
            lineHeight: 1.5,
            color: INK,
            minWidth: 168,
            zIndex: 5,
          }}
        >
          <div style={{ fontWeight: 700, marginBottom: 2 }}>
            {hover.d.offense} · possession {hover.d.drive_number}
          </div>
          <div style={{ color: MUTED }}>
            {hover.d.quarter_label} quarter · started own {hover.d.start_field_position}
          </div>
          <div>
            {hover.d.plays} play{Number(hover.d.plays) === 1 ? "" : "s"}, {hover.d.yards} yards
          </div>
          <div style={{ color: driveColor(hover.d), fontWeight: 600 }}>{hover.d.result_category}</div>
          {hover.d.is_special_teams_touchdown ? (
            <div style={{ color: NAVY }}>
              {hover.d.special_teams_score_type} touchdown — {hover.d.defense}
            </div>
          ) : (
            Number(hover.d.defensive_points_scored) > 0 && (
              <div style={{ color: NAVY }}>
                {hover.d.defensive_score_type} — {hover.d.defense} {hover.d.defensive_points_scored} pts
              </div>
            )
          )}
          <div style={{ color: MUTED }}>
            {abbr(hover.d.away_team ?? "")} {hover.d.away_score_after} · {abbr(hover.d.home_team ?? "")}{" "}
            {hover.d.home_score_after}
          </div>
        </div>
      )}
    </div>
  );
}


// =====================================================================
//  Games report — the page
//
//  One scoreboard card per game, from the dashboard's own query (named
//  in its # artifact, so the 2025 and 2026 reports share this component).
//  The .malloy file owns every filter (team, conference, division, week
//  and the pinned season); this component owns what the reader does with
//  the result: the sort order, paging, and the drive charts.
//
//  View-state lives in the URL next to the givens, so a sorted, filtered
//  page is a link: ~sort=thrill, ~orient=down, ~legend=false.
//
//  Drive charts are open by default. Their drives are fetched for the
//  games on screen in ONE query per page of cards — not one per game —
//  and kept per game id, so re-sorting, re-filtering or paging back over
//  games already drawn never asks for them again.
// =====================================================================

const SURFACE = "#ffffff";
const BORDER = "#e5e7eb";
const INK_2 = "#4b5563";
const PAGE_SIZE = 40;

// One hue, darkening with the score: the tier is also written out beside
// the number, so the color only ever repeats what the text says.
const THRILL_COLORS: Record<string, string> = {
  "Instant classic": "#a63d12",
  Thriller: "#e2703a",
  "Good game": "#eeaa82",
  Routine: "#d3d6db",
};

const THRILL_PARTS: [string, string, number][] = [
  ["thrill_closeness", "Close final", 35],
  ["thrill_late_drama", "Close entering the 4th", 20],
  ["thrill_comeback", "Comeback win", 10],
  ["thrill_overtime", "Overtime", 15],
  ["thrill_scoring", "Scoring", 12],
  ["thrill_upset", "Elo upset", 10],
  ["thrill_stakes", "Playoff stakes", 8],
];

const pickValues = (v: any) => {
  try {
    return (filters.values ? filters.values(v) : []).filter(Boolean);
  } catch {
    return [];
  }
};

const num = (v: any): number | null => (v == null || v === "" ? null : Number(v));

/** Alabama's → Alabama's, Texas' → Texas'. */
const possessive = (name: string) => `${name}${/s$/i.test(name) ? "'" : "'s"}`;

/**
 * StartDate is a naive US/Pacific wall-clock time (see games.malloy), so
 * it is read and formatted as UTC — which leaves the wall clock alone —
 * and labelled PT. A value without a zone would otherwise be read as the
 * VIEWER's local time and shift by their offset.
 */
const kickoffDate = (v: any): Date | null => {
  if (v == null || v === "") return null;
  if (v instanceof Date) return v;
  const s = String(v).trim().replace(" ", "T");
  return new Date(/[zZ]|[+-]\d\d:?\d\d$/.test(s) ? s : `${s}Z`);
};

const kickoffTime = (g: any) => kickoffDate(g.start_date)?.getTime() ?? null;

const fmtKickoff = (g: any) => {
  const d = kickoffDate(g.start_date);
  if (!d) return "";
  const day = d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", timeZone: "UTC" });
  if (g.start_time_tbd) return `${day} · time TBD`;
  const time = d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", timeZone: "UTC" });
  return `${day} · ${time} PT`;
};

const isPlayed = (g: any) => !!g.completed && num(g.home_points) != null && num(g.away_points) != null;
const canChart = (g: any) => isPlayed(g) && !!g.has_drive_detail;

const winnerOf = (g: any) => {
  if (!isPlayed(g)) return null;
  const h = Number(g.home_points);
  const a = Number(g.away_points);
  return h > a ? g.home_team : a > h ? g.away_team : null;
};

// ---- sorting ---------------------------------------------------------
// Every sort puts games it has nothing to say about (unplayed games under
// "Closest finish", non-upsets under "Biggest upset") after the rest, in
// kickoff order, rather than dropping them.
type SortSpec = { value: string; text: string; key: (g: any) => number | null; dir: 1 | -1 };

const SORTS: SortSpec[] = [
  { value: "kickoff", text: "Kickoff", key: kickoffTime, dir: 1 },
  { value: "latest", text: "Latest results", key: (g) => (isPlayed(g) ? kickoffTime(g) : null), dir: -1 },
  { value: "thrill", text: "Thrill index", key: (g) => num(g.thrill_index), dir: -1 },
  { value: "excitement", text: "CFBD excitement", key: (g) => num(g.excitement_index), dir: -1 },
  { value: "closest", text: "Closest finish", key: (g) => (isPlayed(g) ? num(g.victory_margin) : null), dir: 1 },
  { value: "points", text: "Most points", key: (g) => (isPlayed(g) ? num(g.total_points) : null), dir: -1 },
  {
    value: "upset",
    text: "Biggest upset",
    key: (g) => (isPlayed(g) && g.is_elo_upset ? Math.abs(Number(g.pregame_elo_edge) || 0) : null),
    dir: -1,
  },
];

function sortGames(rows: any[], sortValue: string) {
  const spec = SORTS.find((s) => s.value === sortValue) || SORTS[0];
  return [...rows].sort((a, b) => {
    const ka = spec.key(a);
    const kb = spec.key(b);
    if (ka == null && kb != null) return 1;
    if (kb == null && ka != null) return -1;
    if (ka != null && kb != null && ka !== kb) return (ka - kb) * spec.dir;
    return (kickoffTime(a) ?? 0) - (kickoffTime(b) ?? 0) || Number(a.game_id) - Number(b.game_id);
  });
}

// ---- small pieces ----------------------------------------------------
const controlLabel: React.CSSProperties = {
  color: "var(--dash-muted, #888)", marginBottom: 2, fontSize: 11,
  fontWeight: 500, textTransform: "uppercase", letterSpacing: ".03em",
};
const selectStyle: React.CSSProperties = {
  fontSize: 13, padding: "4px 7px", borderRadius: 6,
  border: "1px solid var(--dash-border, #ccc)",
  background: "var(--dash-control-bg, white)",
  color: "var(--dash-fg, #1a1a1a)",
};

/** A view-state picker shaped like the <Given> controls beside it. */
function ViewSelect({ label, value, onChange, options, hint }: {
  label: string; value: string; onChange: (v: string) => void;
  options: { value: string; text: string }[]; hint?: string;
}) {
  return (
    <div style={{ display: "flex", flexDirection: "column" }}>
      <div style={controlLabel}>{label}</div>
      <select value={value} onChange={(e) => onChange(e.target.value)} style={selectStyle}>
        {options.map((o) => (
          <option key={o.value} value={o.value}>{o.text}</option>
        ))}
      </select>
      {hint !== undefined && (
        <div style={{ fontSize: 10, color: "var(--dash-muted, #888)", marginTop: 2, minHeight: 12 }}>{hint}</div>
      )}
    </div>
  );
}

function Tag({ children, strong }: { children: React.ReactNode; strong?: boolean }) {
  return (
    <span
      style={{
        fontSize: 10.5, fontWeight: 600, letterSpacing: ".02em", padding: "1px 7px",
        borderRadius: 999, whiteSpace: "nowrap",
        background: strong ? "#fbe7dc" : "#f1f3f5",
        color: strong ? "#8a3310" : INK_2,
      }}
    >
      {children}
    </span>
  );
}

/** Line scores, with every overtime period folded into one OT column. */
function periodCells(line: any, played: boolean) {
  const parts = String(line ?? "").split(",").map((s) => s.trim()).filter((s) => s !== "");
  if (!played || !parts.length) return null;
  const reg = parts.slice(0, 4);
  while (reg.length < 4) reg.push("");
  const ot = parts.slice(4);
  return { reg, ot: ot.length ? String(ot.reduce((s, p) => s + (Number(p) || 0), 0)) : null };
}

function Scoreboard({ g }: { g: any }) {
  const played = isPlayed(g);
  const winner = winnerOf(g);
  const away = periodCells(g.away_line_scores, played);
  const home = periodCells(g.home_line_scores, played);
  const hasOT = !!(away?.ot || home?.ot);
  const hasLines = !!(away && home);

  const cell: React.CSSProperties = { padding: "3px 0", width: 26, textAlign: "center", color: MUTED, fontSize: 12 };
  const rows = [
    { team: g.away_team, conf: g.away_conference, pts: g.away_points, seed: g.away_seed, line: away },
    { team: g.home_team, conf: g.home_conference, pts: g.home_points, seed: g.home_seed, line: home },
  ];

  return (
    <table style={{ borderCollapse: "collapse", width: "100%", fontVariantNumeric: "tabular-nums" }}>
      {hasLines && (
        <thead>
          <tr>
            <th />
            {["1", "2", "3", "4"].map((p) => (
              <th key={p} style={{ ...cell, fontSize: 10, fontWeight: 500 }}>{p}</th>
            ))}
            {hasOT && <th style={{ ...cell, fontSize: 10, fontWeight: 500 }}>OT</th>}
            <th style={{ ...cell, fontSize: 10, fontWeight: 500, width: 38 }}>T</th>
          </tr>
        </thead>
      )}
      <tbody>
        {rows.map((r, i) => {
          const won = winner != null && sameTeam(winner, r.team);
          return (
            <tr key={i}>
              <td style={{ padding: "3px 10px 3px 0", minWidth: 0 }}>
                {r.seed != null && (
                  <span style={{ fontSize: 10.5, color: MUTED, marginRight: 5 }}>#{r.seed}</span>
                )}
                <span style={{ fontSize: 15, fontWeight: won ? 700 : played ? 500 : 600, color: played && !won ? INK_2 : INK }}>
                  {r.team}
                </span>
                {r.conf && <span style={{ fontSize: 11, color: MUTED, marginLeft: 7 }}>{r.conf}</span>}
              </td>
              {hasLines && r.line!.reg.map((p: string, j: number) => <td key={j} style={cell}>{p}</td>)}
              {hasLines && hasOT && <td style={cell}>{r.line!.ot ?? "0"}</td>}
              <td style={{ padding: "3px 0", width: 38, textAlign: "right", fontSize: 18, fontWeight: won ? 800 : 600, color: won ? INK : INK_2 }}>
                {played ? r.pts : ""}
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}

function ThrillMeter({ g }: { g: any }) {
  const v = num(g.thrill_index);
  if (!isPlayed(g) || v == null) {
    // unplayed: what the ratings expect instead
    const edge = num(g.pregame_elo_edge);
    if (edge == null) return <div style={{ fontSize: 12, color: MUTED }}>Not played yet</div>;
    const homeWin = 1 / (1 + Math.pow(10, -edge / 400));
    const fav = homeWin >= 0.5 ? g.home_team : g.away_team;
    return (
      <div style={{ fontSize: 12, color: INK_2, lineHeight: 1.45 }}>
        <div style={{ color: MUTED, fontSize: 10.5, textTransform: "uppercase", letterSpacing: ".05em" }}>Elo favorite</div>
        <div style={{ fontWeight: 600, color: INK }}>{fav}</div>
        <div>{Math.round(Math.max(homeWin, 1 - homeWin) * 100)}% to win</div>
      </div>
    );
  }
  const color = THRILL_COLORS[g.thrill_tier] || GREY;
  const why = THRILL_PARTS.map(([k, label, max]) => [label, num(g[k]) ?? 0, max] as const).filter(([, pts]) => pts >= 0.5);
  return (
    <div style={{ minWidth: 0 }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 6 }}>
        <span style={{ fontSize: 26, fontWeight: 800, color: INK, fontVariantNumeric: "tabular-nums", lineHeight: 1 }}>{v}</span>
        <span style={{ fontSize: 10.5, color: MUTED, textTransform: "uppercase", letterSpacing: ".05em" }}>Thrill</span>
      </div>
      <div style={{ height: 6, background: "#eef0f2", borderRadius: 3, margin: "6px 0 5px", overflow: "hidden" }}>
        <div style={{ width: `${Math.max(2, v)}%`, height: "100%", background: color, borderRadius: 3 }} />
      </div>
      <div style={{ fontSize: 12, color: INK_2, fontWeight: 600 }}>{g.thrill_tier}</div>
      <div style={{ fontSize: 10.5, color: MUTED, marginTop: 2, lineHeight: 1.4 }}>
        {why.map(([label, pts]) => `${label} ${Math.round(pts)}`).join(" · ")}
      </div>
      {num(g.excitement_index) != null && (
        <div style={{ fontSize: 10.5, color: MUTED, marginTop: 2 }}>CFBD excitement {Number(g.excitement_index).toFixed(1)}</div>
      )}
    </div>
  );
}

/** "See all of TCU's games" — the same place the Team picker would take you. */
function TeamLinks({ g, team, onPick }: { g: any; team: string; onPick: (t: string) => void }) {
  const teams = [g.away_team, g.home_team].filter((t) => t && !(team && sameTeam(team, t)));
  if (!teams.length) return null;
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 2, marginTop: 8 }}>
      {teams.map((t) => (
        <button
          key={t}
          onClick={() => onPick(t)}
          title={`Show every ${t} game this season`}
          style={{
            background: "none", border: 0, padding: 0, cursor: "pointer", textAlign: "left",
            font: "inherit", fontSize: 11.5, color: "var(--dash-accent, #2a78d6)",
          }}
        >
          See all of {possessive(t)} games →
        </button>
      ))}
    </div>
  );
}

// ---- drive chart legend ---------------------------------------------
// The chart's own palette (drive-chart.part.tsx), in words. Every mark on
// the chart also carries a text label, so this is a convenience rather
// than the only way to read it.
const LEGEND: { color: string; dash?: boolean; dot?: boolean; label: string }[] = [
  { color: NAVY, label: "Touchdown" },
  { color: BLUE, label: "Field goal" },
  { color: ORANGE, label: "Drive lost yardage" },
  { color: GREY, label: "Punt, turnover or clock" },
  { color: NAVY, dash: true, label: "Defensive touchdown" },
  { color: NAVY, dot: true, label: "Special teams touchdown (kickoff, punt, blocked kick)" },
  { color: KO_GREY, dash: true, label: "Kickoff (KO) and change of possession" },
];

function DriveLegend() {
  return (
    <div
      style={{
        display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px 16px",
        background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 8,
        padding: "8px 12px", marginTop: 8, color: INK,
      }}
    >
      {LEGEND.map((item) => (
        <span key={item.label} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 11.5 }}>
          <svg width="20" height="10" aria-hidden="true">
            <line
              x1="1" y1="5" x2="19" y2="5"
              stroke={item.color}
              strokeWidth={item.dash ? 1.5 : 2}
              strokeDasharray={item.dot ? "1 3.5" : item.dash ? "3 3" : undefined}
              strokeLinecap="round"
            />
          </svg>
          {item.label}
        </span>
      ))}
      <span style={{ fontSize: 11, color: MUTED }}>
        Each drive runs from where the offense took over to where the possession ended; the label is the result.
      </span>
    </div>
  );
}

function GameCard({ g, drives, drivesError, focusTeam, orient, onPickTeam }: {
  g: any;
  /** This game's drives: undefined while they load, [] when the feed has none. */
  drives?: any[];
  drivesError?: string | null;
  focusTeam?: string;
  orient: DriveOrient;
  onPickTeam: (t: string) => void;
}) {
  const [open, setOpen] = useState(true);
  const chartable = canChart(g);

  const tags: React.ReactNode[] = [];
  if (g.playoff_round) tags.push(<Tag key="po" strong>{g.playoff_round}</Tag>);
  if (g.bowl && g.bowl !== g.playoff_round) tags.push(<Tag key="bowl">{g.bowl}</Tag>);
  if (isPlayed(g) && g.is_overtime) tags.push(<Tag key="ot" strong>Overtime</Tag>);
  if (isPlayed(g) && g.is_comeback_win) tags.push(<Tag key="cb" strong>Comeback</Tag>);
  if (isPlayed(g) && g.is_elo_upset) tags.push(<Tag key="up" strong>Upset</Tag>);
  if (g.conference_game) tags.push(<Tag key="conf">Conference game</Tag>);
  if (g.neutral_site) tags.push(<Tag key="ns">Neutral site</Tag>);

  return (
    <article
      style={{
        background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 10,
        padding: "12px 16px", marginTop: 10, color: INK,
      }}
    >
      <header style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "4px 10px", marginBottom: 6 }}>
        <span style={{ fontSize: 12, color: INK_2, fontWeight: 600 }}>{g.week_label}</span>
        <span style={{ fontSize: 12, color: MUTED }}>{fmtKickoff(g)}</span>
        {g.venue && <span style={{ fontSize: 12, color: MUTED }}>· {g.venue}</span>}
        {g.attendance != null && isPlayed(g) && (
          <span style={{ fontSize: 12, color: MUTED }}>· {Number(g.attendance).toLocaleString()} fans</span>
        )}
        <span style={{ display: "flex", gap: 5, flexWrap: "wrap", marginLeft: "auto" }}>{tags}</span>
      </header>

      <div style={{ display: "flex", flexWrap: "wrap", gap: "10px 28px", alignItems: "flex-start" }}>
        <div style={{ flex: "1 1 360px", minWidth: 0 }}>
          <Scoreboard g={g} />
          {g.notes && <div style={{ fontSize: 11, color: MUTED, marginTop: 3 }}>{g.notes}</div>}
        </div>
        <div style={{ flex: "0 1 210px", minWidth: 150 }}>
          <ThrillMeter g={g} />
          <TeamLinks g={g} team={focusTeam || ""} onPick={onPickTeam} />
        </div>
      </div>

      {chartable && (
        <div style={{ marginTop: 8 }}>
          <button
            onClick={() => setOpen(!open)}
            style={{
              fontSize: 12, padding: "3px 10px", borderRadius: 6, cursor: "pointer",
              border: `1px solid ${BORDER}`, background: open ? "#f3f4f6" : SURFACE, color: INK_2,
            }}
          >
            {open ? "Hide drive chart" : "Show drive chart"}
          </button>
          {open && (
            <div style={{ marginTop: 10 }}>
              {drives === undefined ? (
                drivesError ? (
                  <div style={{ fontSize: 12, color: "var(--dash-danger, #b91c1c)" }}>{drivesError}</div>
                ) : (
                  // hold roughly the chart's height, so cards below don't jump when it lands
                  <div style={{ fontSize: 12, color: MUTED, height: 420 }}>Loading drives…</div>
                )
              ) : drives.length ? (
                <DriveChart
                  game={{ home_team: g.home_team, away_team: g.away_team, rows: drives }}
                  focusTeam={focusTeam}
                  orient={orient}
                />
              ) : (
                <div style={{ fontSize: 12, color: MUTED }}>No drive data for this game.</div>
              )}
            </div>
          )}
        </div>
      )}
    </article>
  );
}

/**
 * Drives for the games on screen, fetched a page at a time and kept by game
 * id for as long as the page is open. Returns the cache (read it with
 * .get(id)) and the last error, if any.
 */
function useDrivesFor(gameIds: number[]) {
  const cache = useRef(new Map<number, any[]>());
  const inFlight = useRef(new Set<number>());
  const [, repaint] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const key = gameIds.join(",");

  useEffect(() => {
    const missing = gameIds.filter((id) => !cache.current.has(id) && !inFlight.current.has(id));
    for (let i = 0; i < missing.length; i += PAGE_SIZE) {
      const batch = missing.slice(i, i + PAGE_SIZE);
      batch.forEach((id) => inFlight.current.add(id));
      // Game ids are integers, so the filter lists need no escaping. The
      // DRIVE_GAMES given narrows the drive model to these games BEFORE its
      // season-wide window passes (drive-games.malloy) — the where: alone
      // would only filter after them.
      const ids = batch.join(", ");
      runData(`drives -> game_drive_chart + { where: GameId ~ f'${ids}' }`, { DRIVE_GAMES: ids })
        .then((rows: any[]) => {
          const byGame = new Map<number, any[]>(batch.map((id) => [id, []]));
          rows.forEach((r) => byGame.get(Number(r.game_id))?.push(r));
          byGame.forEach((list, id) => {
            list.sort((a, b) => Number(a.drive_number) - Number(b.drive_number));
            cache.current.set(id, list);
          });
          setError(null);
        })
        .catch((e: any) => setError(String(e?.message ?? e)))
        .finally(() => {
          batch.forEach((id) => inFlight.current.delete(id));
          repaint((n) => n + 1);
        });
    }
  }, [key]);

  return { drives: cache.current, error };
}

export default function Dashboard({ dashboard, givens }: any) {
  // the dashboard's own query, named in its # artifact tag
  const list = useQuery({ query: dashboard?.query, givens });
  const teamGiven = useGiven("TEAM");
  const conferenceGiven = useGiven("CONFERENCE");
  const weekGiven = useGiven("GAME_WEEK");
  const divisionGiven = useGiven("DIVISION");
  const team: string = useMemo(() => pickValues(teamGiven.value)[0] || "", [teamGiven.value]);
  const conference: string = useMemo(() => pickValues(conferenceGiven.value)[0] || "", [conferenceGiven.value]);

  const [sort, setSort] = useUrlState("sort", "kickoff");
  const [orient, setOrient] = useUrlState("orient", "up");
  const [legend, setLegend] = useUrlState("legend", true);
  const [shown, setShown] = useState(PAGE_SIZE);

  // Picking a conference drops the team: a team plus somebody else's
  // conference matches nothing, and the conference is the wider question.
  const lastConference = useRef(conference);
  useEffect(() => {
    if (lastConference.current === conference) return;
    lastConference.current = conference;
    if (team) teamGiven.set("");
  }, [conference, team]);

  // A team link means "show me this team", so it clears the filters that
  // would hide the rest of that team's season.
  const pickTeam = (t: string) => {
    teamGiven.set(filters.oneOf(t));
    if (conference) conferenceGiven.set("");
    if (pickValues(weekGiven.value).length) weekGiven.set("");
    if (pickValues(divisionGiven.value).length) divisionGiven.set("");
    lastConference.current = "";
    window.scrollTo({ top: 0 });
  };

  const rows: any[] = list.rows || [];
  const sorted = useMemo(() => sortGames(rows, sort), [rows, sort]);
  useEffect(() => setShown(PAGE_SIZE), [rows, sort]);

  const visible = sorted.slice(0, shown);
  const { drives, error: drivesError } = useDrivesFor(
    list.loading ? [] : visible.filter(canChart).map((g) => Number(g.game_id))
  );

  const played = rows.filter(isPlayed);
  const avgThrill = played.length
    ? played.reduce((s, g) => s + (num(g.thrill_index) ?? 0), 0) / played.length
    : null;
  const record = team
    ? played.reduce(
        (acc, g) => {
          const w = winnerOf(g);
          if (w && sameTeam(w, team)) acc.w++;
          else if (w) acc.l++;
          return acc;
        },
        { w: 0, l: 0 }
      )
    : null;

  const season = rows[0]?.season ?? String(dashboard?.title || "").match(/\d{4}/)?.[0] ?? "";
  const title = dashboard?.title || `${season} Games`;

  return (
    <div style={{ maxWidth: 1320, margin: "0 auto", padding: "20px 20px 48px" }}>
      <h1 style={{ margin: "0 0 2px", fontSize: 26, fontWeight: 700, letterSpacing: "-0.01em" }}>
        {team ? `${team} · ${title}` : title}
      </h1>
      <p style={{ margin: "0 0 14px", fontSize: 13, color: "var(--dash-muted, #6b7280)" }}>
        Every game of the {season} season, with its line score, thrill index and drive chart. Pick a
        team, conference or week to narrow the list.
      </p>

      <Controls>
        <Given name="TEAM" />
        <Given name="CONFERENCE" />
        <Given name="GAME_WEEK" />
        <Given name="DIVISION" />
        <ViewSelect label="Sort by" value={sort} onChange={setSort} options={SORTS} hint="" />
        {team && (
          <ViewSelect
            label={`${team} drives`}
            value={orient}
            onChange={setOrient}
            options={[
              { value: "up", text: "Up" },
              { value: "down", text: "Down" },
              { value: "default", text: "Default" },
            ]}
            hint={orient === "default" ? "Home team drives down" : "The field turns over as needed"}
          />
        )}
      </Controls>

      {!list.loading && !list.error && (
        <>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "4px 18px", alignItems: "baseline", margin: "14px 0 2px", fontSize: 13, color: "var(--dash-muted, #6b7280)" }}>
            <span>
              <strong style={{ color: "var(--dash-fg, #16181c)" }}>{rows.length.toLocaleString()}</strong> games
              {" · "}
              <strong style={{ color: "var(--dash-fg, #16181c)" }}>{played.length.toLocaleString()}</strong> played
            </span>
            {record && played.length > 0 && (
              <span>
                {team} <strong style={{ color: "var(--dash-fg, #16181c)" }}>{record.w}–{record.l}</strong>
              </span>
            )}
            {avgThrill != null && (
              <span>
                average thrill <strong style={{ color: "var(--dash-fg, #16181c)" }}>{avgThrill.toFixed(0)}</strong>
              </span>
            )}
            <details style={{ fontSize: 12 }}>
              <summary style={{ cursor: "pointer" }}>How the thrill index works</summary>
              <div style={{ maxWidth: 640, lineHeight: 1.5, marginTop: 4 }}>
                A 0–100 score from the box score, so every completed game has one. Points for a close
                final (up to 35, gone at a 28-point margin), a close game entering the fourth quarter
                (20, gone at 17), a comeback win (10), overtime (15), combined scoring (12, full at 80
                points), an Elo upset (10, full at a 250-point rating gap) and a playoff game (8), capped
                at 100. Instant classic at 75+, Thriller 55+, Good game 35+. CFBD's own excitement
                rating, built from win-probability swings, is shown beside it where CFBD has published one.
              </div>
            </details>
            <button
              onClick={() => setLegend(!legend)}
              style={{
                background: "none", border: 0, padding: 0, cursor: "pointer", font: "inherit",
                fontSize: 12, color: "var(--dash-accent, #2a78d6)",
              }}
            >
              {legend ? "Hide drive chart legend" : "Show drive chart legend"}
            </button>
          </div>
          {legend && <DriveLegend />}
        </>
      )}

      {list.loading && <div style={{ fontSize: 13, color: MUTED, marginTop: 16 }}>Loading games…</div>}
      {list.error && <div style={{ fontSize: 13, color: "var(--dash-danger, #b91c1c)", marginTop: 16 }}>{String(list.error)}</div>}
      {!list.loading && !list.error && rows.length === 0 && (
        <div style={{ fontSize: 13, color: MUTED, marginTop: 16 }}>No games match these filters.</div>
      )}

      {!list.loading && !list.error && (
        <>
          {visible.map((g) => (
            <GameCard
              key={g.game_id}
              g={g}
              drives={drives.get(Number(g.game_id))}
              drivesError={drivesError}
              focusTeam={team || undefined}
              orient={orient as DriveOrient}
              onPickTeam={pickTeam}
            />
          ))}
          {sorted.length > shown && (
            <div style={{ textAlign: "center", marginTop: 16 }}>
              <button
                onClick={() => setShown(shown + PAGE_SIZE)}
                style={{
                  fontSize: 13, padding: "7px 16px", borderRadius: 8, cursor: "pointer",
                  border: "1px solid var(--dash-border, #d1d5db)", background: "var(--dash-control-bg, #fff)",
                  color: "var(--dash-fg, #1a1a1a)",
                }}
              >
                Show {Math.min(PAGE_SIZE, sorted.length - shown)} more of {sorted.length - shown} remaining
              </button>
            </div>
          )}
        </>
      )}
    </div>
  );
}
